### ISSUE TITLE
Unable to install on my main drive

### ISSUE THREAD

**Issue by TheGman1102** [kulvind3r/GamingGaiden#13]
I execute the bat file and then this message comes up:

"Cannot install to OS i.e. C: drive. Please choose a different location. Press any key to exit..."

Any help is welcome.

**Comment by kulvind3r** [comment]
What is so difficult? Just do what the message tells you... 

Just Use D: drive.

**Comment by kulvind3r** [comment]
Closing the invalid issue.

**Comment by TheGman1102** [comment]
> What is so difficult? Just do what the message tells you...
> 
> Just Use D: drive.

I know this is almost mythical on Github, but guess what, I'm not as proficient on fiddling through programs and stuff, I'm just a casual PC user, and I couldn't make it work by myself. I saw this program on a reddit post, and just wanted to test it out. But I guess I'm not using it, F this.

**Comment by kulvind3r** [comment]
The above comment was deleted for un-necessary hostility and un-warranted profane language. 

Another user shared their limited tech knowledge and inability to use other drives in a much co-operative manner on a reddit thread and that resulted in their request of a more seamless installation method getting implemented.

Latest release supports C drive and doesn't require any tech knowledge on user's behalf.
