### ISSUE TITLE
Unable to create a shortcut

### ISSUE THREAD

**Issue by AmetistoFF** [kulvind3r/GamingGaiden#14]
**Describe the bug**
When using Install.bat, the installer fails to create the shortcut. Also it seems that because of this, the program fails to install. No files or folders are found. The translation of error message is: 
Unable to save the shortcut "C:\Users\peshk\Desktop\Gaming Gaiden.lnk".
line:1 symbol:408
+ ... tory = 'D:\GamingGaiden'; $Shortcut.WindowStyle = 7; **$Shortcut.Save()**
+                                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException

The system's unable to find given directory.

**To Reproduce**
Open Install.bat in the D; drive.

**Expected behavior**
The thing's supposed to install.

**Screenshots**
Included.

**Log:**
 No log has been created.

**Additional context**
I use the installer from the D; drive. This is also why it bypasses the error message, telling you not to install the app in the C;
![8RMxnmdMAe0](https://github.com/kulvind3r/GamingGaiden/assets/39126265/f5395d60-f191-4959-b19e-bd2674ee5fe5)

**Comment by kulvind3r** [comment]
Hmm, i am not sure know what is causing this behavior on your machine... you are doing the things correctly. install.bat has to be just run from a non C: drive location and it should create the shortcuts.

We can try to create shortcut first in the install directory and then copying it to Desktop. Basically just doing the reverse of current approach. That should at least create a shortcut for you in the install directory which you can use to start the application. You can copy it to desktop if needed and to "shell:startup" directory if you want to auto start as well.

Here is a modified install.bat code. Delete everything inside install.bat file and paste the full code from the below paste bin in it.
Then run install.bat again. See if that works. Let me know if it does not.

https://pastebin.com/YZKt9SaQ

**Comment by AmetistoFF** [comment]
Yep, it created the shortcut in the install directory. After this everything seems to be working fine.

**Comment by kulvind3r** [comment]
Great. This is a strange behavior.... copying to desktop works but directly creating a shortcut on desktop does not work for some users it seems. Will look into it. 

Closing the issue for now.

**Comment by kulvind3r** [comment]
Have pushed the fix. Will be part of the next release
