### ISSUE TITLE
Time not being tracked properly 

### ISSUE THREAD

**Issue by vitinhu1591** [kulvind3r/GamingGaiden#18]
**Describe the bug**
i'm using Dolphin 2409, noticed the time in the save file of LoZ: Twilight Princess was way bigger than what Gaming Gaiden has tracked, so i did a test, started the game at 13:30, at this time the total playtime was: 19:08, played the game until 14:23, the total play time was now 19:19

**Comment by kulvind3r** [comment]
Can you share the `Gaming Gaiden.log` File. You can find it in Install directory of the app. 

To Open install directory use the app menu `Settings => Open Install Directory` option

**Comment by vitinhu1591** [comment]
[GamingGaiden.log](https://github.com/user-attachments/files/17080180/GamingGaiden.log)

**Comment by kulvind3r** [comment]
This log is empty. You must have restarted Gaming Gaiden. Log file is reset when application is restarted.

You need to submit the log file after playing the game and noticing the problem.

Play the game again. After you finish check the time recorded, if the time is not correct, immediately share the log file.

Also,

Have you checked the "Idle Time" stat? It is possible that the missing time is being recorded as Idle time and hence being removed from game play time.

**Comment by kulvind3r** [comment]
Closing the issue as it is not re producible on my end and there has been no response from OP for 4 days.
