### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by liangforstudy** [kulvind3r/GamingGaiden#20]
![image](https://github.com/user-attachments/assets/9ada1214-383e-4c0c-adc8-3b011d51482f)

Help! I tried running as admin, still didn't work!

**Comment by liangforstudy** [comment]
[GamingGaiden.log](https://github.com/user-attachments/files/17264593/GamingGaiden.log)

**Comment by kulvind3r** [comment]
Open a Powershell window as admin and run below command to allow powershell modules to load on your system. Choose `Yes` when prompted.

    Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser


Then try to run the app again. It should work.

**Comment by liangforstudy** [comment]
Hi, I did the steps as above, but the gaming guardian app didn't appear in my start menu.
also, I found that your app created a 2.60GB folder in `C:\ProgramData\GamingGaiden` why is that so?
I'm looking for a lightweight application, preferably a few megabytes in size to keep track of the time i spent in minecraft dungenons, but not this when it's taking up 2.60Gb of space ;/

**Comment by kulvind3r** [comment]
The application doesn't use 2.6 GB of space. I have over record of 1200 Hrs of game play in 105 games and the app uses just 10 MB of space. See the attached screenshot.

If you have run the above fix correctly, you can delete the app folder completely and install it one more time and then try starting it. Shortcuts should be created on your desktop and start menu.

If it still doesn't work. Then i am afraid i can't help you.

![image](https://github.com/user-attachments/assets/634cc7f7-b187-44b3-a8d5-0dd67a2ddcef)
![image](https://github.com/user-attachments/assets/0dcf7778-0330-4bc3-b153-d3556d679bd8)

**Comment by kulvind3r** [comment]
Non reproducible issue... user's problems are specific to their own system. Closing.
