### ISSUE TITLE
No .exe found

### ISSUE THREAD

**Issue by FTH99** [kulvind3r/GamingGaiden#21]
Hello,
thank you for your software! I'd love to try it.
When I try to install it (via GUI or PS) everything goes well but at the end, there is no .exe to run the software. Do you have a fix for this?

**Comment by FTH99** [comment]
Don't know what happened but it worked when I downloaded it the 3rd time. Who would have thought. Thanks.

**Comment by kulvind3r** [comment]
There is no GUI or PS based installer for the application. There is just one file called "install.bat" that you have to run to install the app.

The app gets install in `C:\ProgramData\GamingGaiden` and the exe to run the app is also in there. On installation app creates shortcuts to the exe on desktop and in start menu.

Not sure why you had to download it 3 times or how you installed it. 

But if you following the [How to Install](https://github.com/kulvind3r/GamingGaiden#how-to-install--upgrade--use) then it should have worked the first time.

Good if it worked for you in the end. Check out the install instructions if you have not already.

**Comment by FTH99** [comment]
Hey, I think I used github itself wrong - downloaded the code twice instead of the release... I followed your instructions but I had no instructions for github. Haha.
Thank you! Software works fine and I already love it.
