### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by Minmus-Mun** [kulvind3r/GamingGaiden#24]
So as soon as I downloaded the ZIP my anti virus was rejecting it as a trojan great start, I had to disable it, then Windows it self asked me if I'm sure I want to run the installer, I ran the installer which finished, and then once I attempted to open the actual exe from the installed repository, it gave me this : 2024-12-17T12:29:47 : Exception: Невозможно загрузить файл C:\ProgramData\GamingGaiden\modules\PSSQLite\1.1.0\PSSQLite.psm1, так как выполнение сценариев отключено в этой системе. Для получения дополнительных сведений см. about_Execution_Policies по адресу https:/go.microsoft.com/fwlink/?LinkID=135170. (I even changed my Execution Policy which didn't work so I switched it back, ran with Administrator, didn't work. I might be missing something but the download instructions didn't have anything, and I was not missing that file I checked.)

**Comment by kulvind3r** [comment]
Hey you closed the issue very quickly... hope things worked out for you. But anyway, Please see the following parts...

1. [How to Install](https://github.com/kulvind3r/GamingGaiden#how-to-install--upgrade--use)
2. Windows Smart Screen [Unknown Publisher Warning](https://github.com/kulvind3r/GamingGaiden#unknown-publisher)
3. [Antivirus False Postive](https://github.com/kulvind3r/GamingGaiden#antivirus-false-positives)

If you first set the execution policy correctly and then installed correctly following instructions i.e. using bat file.  Then application should work from the shortcuts that are created on desktop / start menu.

Your exception seems to indicate that you failed to set the execution policy in first start. After you set the execution policy then installing , the app should start correctly.
